### ISSUE TITLE
トップ画面のモックを作成する

### ISSUE THREAD

**Issue by ayaka2019436** [ayaka2019436/quiz-app#1]
## 概要 (Summary):
タイトルをクリックしたらトップに遷移する

**Comment by abe127** [comment]
- トップ画面の背景を考える
  - サブタイトルの文字が背景と同化しないように気を付ける
    - サブタイトルの文字を明るくしたり、サブタイトルの部分だけ背景色を指定したりして工夫する
  - 最悪背景画像はなくてもいいかも
    - 背景色に薄い色を入れて白を回避するとか
- `angular-app/src/app/app-routing.module.ts`にrouteの設定をする
  - toolbarのタイトルをクリックした時にトップ画面に遷移させるために必要
- toolbarのタイトルをクリックした時にトップ画面に遷移させる
- `toolber`を`toolbar`に直す
  - コンポーネントを作り直した方がはやいかも
- `angular-app/src/assets/_color.scss`を適用する
  - toolbarとかサブタイトルに$blackを適用する
